# -*- coding: utf-8 -*-
"""Homework #1 Linear Regression Part 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1keZh-F3vTbvcEkwNBqKZFW802gSC2-AO
"""

import numpy as np
import pandas as pd
from google.colab import drive
import matplotlib.pyplot as plt
from IPython.display import display

drive.mount('/content/drive')
file_path = '/content/drive/MyDrive/Machine Learning/D3.csv'
D3 = pd.DataFrame(pd.read_csv(file_path))

X1 = D3.values[:, 0]
X2 = D3.values[:, 1]
X3 = D3.values[:,2]
Y = D3.values[:,3]

numOfRows = X1.size
X0 = np.ones((numOfRows, 1))

def compute_cost(X, y, theta):

  predictions = X.dot(theta)
  errors = np.subtract(predictions, Y)
  sqrErrors = np.square(errors)
  J = 1 / (2 * numOfRows) * np.sum(sqrErrors)
  return J

def gradient_descent(X, Y, theta, alpha, iterations):

  m = len(Y)
  cost_history = np.zeros(iterations)

  for i in range(iterations):
    predictions = X.dot(theta)
    errors = np.subtract(predictions, Y)
    sum_delta = (alpha / m) * X.transpose().dot(errors);
    theta = theta - sum_delta;
    cost_history[i] = compute_cost(X, Y, theta)

  return theta, cost_history

X1 = X1.reshape(numOfRows,1)
X2 = X2.reshape(numOfRows,1)
X3 = X3.reshape(numOfRows,1)

X_all_vars = np.hstack((X0, X1, X2, X3))

theta_all_vars = np.zeros(4)

iterations = 1500
alpha_01 = 0.01
alpha_1 = 0.1
theta_all_vars_01, cost_history_all_vars_01 = gradient_descent(X_all_vars, Y, theta_all_vars, alpha_01, iterations)

print('Final value of theta X_all_vars_01 =', theta_all_vars_01)

print('cost_history X_all_vars_01 =', cost_history_all_vars_01)

theta_all_vars_1, cost_history_all_vars_1 = gradient_descent(X_all_vars, Y, theta_all_vars, alpha_1, iterations)

print('Final value of theta X_all_vars_1 =', theta_all_vars_1)

print('cost_history X_all_vars_1 =', cost_history_all_vars_1)

plt.plot(range(1, iterations + 1), cost_history_all_vars_01, color='blue')
plt.rcParams["figure.figsize"] = (10, 6)
plt.grid(True)
plt.xlabel('Number of iterations')
plt.ylabel('Cost (J)')
plt.title('Convergence of gradient descent X_all_vars_01')
plt.show()

plt.plot(range(1, iterations + 1), cost_history_all_vars_1, color='blue')
plt.rcParams["figure.figsize"] = (10, 6)
plt.grid(True)
plt.xlabel('Number of iterations')
plt.ylabel('Cost (J)')
plt.title('Convergence of gradient descent X_all_vars_1')
plt.show()