# -*- coding: utf-8 -*-
"""Homework 1 - Linear Regression Part 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/111-KkXf_iWHNLF9fASiZkDaeVn-YjdOY
"""

import numpy as np
import pandas as pd
from google.colab import drive
import matplotlib.pyplot as plt
from IPython.display import display

drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/Machine Learning/D3.csv'
D3 = pd.DataFrame(pd.read_csv(file_path))

X1 = D3.values[:, 0]
X2 = D3.values[:, 1]
X3 = D3.values[:,2]
Y = D3.values[:,3]

numOfRows = X1.size
X0 = np.ones((numOfRows, 1))

X1 = X1.reshape(numOfRows,1)
X1 = np.hstack((X0,X1))

X2 = X2.reshape(numOfRows,1)
X2 = np.hstack((X0,X2))

X3 = X3.reshape(numOfRows,1)
X3 = np.hstack((X0,X3))



def compute_cost(X, y, theta):

  predictions = X.dot(theta)
  errors = np.subtract(predictions, Y)
  sqrErrors = np.square(errors)
  J = 1 / (2 * numOfRows) * np.sum(sqrErrors)
  return J

def gradient_descent(X, Y, theta, alpha, iterations):

  m = len(Y)
  cost_history = np.zeros(iterations)

  for i in range(iterations):
    predictions = X.dot(theta)
    errors = np.subtract(predictions, Y)
    sum_delta = (alpha / m) * X.transpose().dot(errors);
    theta = theta - sum_delta;
    cost_history[i] = compute_cost(X, Y, theta)

  return theta, cost_history


theta_X01 = [0., 0.]
theta_X02 = [0., 0.]
theta_X03 = [0., 0.]
iterations = 1500
alpha_01 = 0.01

theta_X01, cost_history_X01 = gradient_descent(X1, Y, theta_X01, alpha_01, iterations)
theta_X02, cost_history_X02 = gradient_descent(X2, Y, theta_X02, alpha_01, iterations)
theta_X03, cost_history_X03 = gradient_descent(X3, Y, theta_X03, alpha_01, iterations)

theta_X1 = [0., 0.]
theta_X2 = [0., 0.]
theta_X3 = [0., 0.]
alpha_1 = 0.1

theta_X1, cost_history_X1 = gradient_descent(X1, Y, theta_X1, alpha_1, iterations)
theta_X2, cost_history_X2 = gradient_descent(X2, Y, theta_X2, alpha_1, iterations)
theta_X3, cost_history_X3 = gradient_descent(X3, Y, theta_X3, alpha_1, iterations)

print('Final value of theta X01 =', theta_X01)
print('Final value of theta X02 =', theta_X02)
print('Final value of theta X03 =', theta_X03)

print('cost_history X01 =', cost_history_X01)
print('cost_history X02 =', cost_history_X02)
print('cost_history X03 =', cost_history_X03)

plt.scatter(X1[:, 1], Y, color='red', label='Training Data')
plt.plot(X1[:, 1], X1.dot(theta_X01), color='green', label='Linear Regression')
plt.rcParams["figure.figsize"] = (10, 6)
plt.grid(True)
plt.xlabel('X1')
plt.ylabel('D3')
plt.title('Linear Regression Fit X01')
plt.legend()
plt.show()

plt.plot(range(1, iterations + 1), cost_history_X01, color='blue')
plt.rcParams["figure.figsize"] = (10, 6)
plt.grid(True)
plt.xlabel('Number of iterations')
plt.ylabel('Cost (J)')
plt.title('Convergence of gradient descent X01')
plt.show()

plt.scatter(X2[:, 1], Y, color='red', label='Training Data')
plt.plot(X2[:, 1], X2.dot(theta_X02), color='green', label='Linear Regression')
plt.rcParams["figure.figsize"] = (10, 6)
plt.grid(True)
plt.xlabel('X2')
plt.ylabel('D3')
plt.title('Linear Regression Fit X02')
plt.legend()
plt.show()

plt.plot(range(1, iterations + 1), cost_history_X02, color='blue')
plt.rcParams["figure.figsize"] = (10, 6)
plt.grid(True)
plt.xlabel('Number of iterations')
plt.ylabel('Cost (J)')
plt.title('Convergence of gradient descent X02')
plt.show()

plt.scatter(X3[:, 1], Y, color='red', label='Training Data')
plt.plot(X3[:, 1], X3.dot(theta_X03), color='green', label='Linear Regression')
plt.rcParams["figure.figsize"] = (10, 6)
plt.grid(True)
plt.xlabel('X3')
plt.ylabel('D3')
plt.title('Linear Regression Fit X03')
plt.legend()
plt.show()

plt.plot(range(1, iterations + 1), cost_history_X03, color='blue')
plt.rcParams["figure.figsize"] = (10, 6)
plt.grid(True)
plt.xlabel('Number of iterations')
plt.ylabel('Cost (J)')
plt.title('Convergence of gradient descent X03')
plt.show()

print('Final value of theta X1 =', theta_X1)
print('Final value of theta X2 =', theta_X2)
print('Final value of theta X3 =', theta_X3)


print('cost_history X1 =', cost_history_X1)
print('cost_history X2 =', cost_history_X2)
print('cost_history X3 =', cost_history_X3)

plt.scatter(X1[:, 1], Y, color='red', label='Training Data')
plt.plot(X1[:, 1], X1.dot(theta_X1), color='green', label='Linear Regression')
plt.rcParams["figure.figsize"] = (10, 6)
plt.grid(True)
plt.xlabel('X1')
plt.ylabel('D3')
plt.title('Linear Regression Fit X1')
plt.legend()
plt.show()

plt.plot(range(1, iterations + 1), cost_history_X1, color='blue')
plt.rcParams["figure.figsize"] = (10, 6)
plt.grid(True)
plt.xlabel('Number of iterations')
plt.ylabel('Cost (J)')
plt.title('Convergence of gradient descent X1')
plt.show()

plt.scatter(X2[:, 1], Y, color='red', label='Training Data')
plt.plot(X2[:, 1], X2.dot(theta_X2), color='green', label='Linear Regression')
plt.rcParams["figure.figsize"] = (10, 6)
plt.grid(True)
plt.xlabel('X2')
plt.ylabel('D3')
plt.title('Linear Regression Fit X2')
plt.legend()
plt.show()

plt.plot(range(1, iterations + 1), cost_history_X2, color='blue')
plt.rcParams["figure.figsize"] = (10, 6)
plt.grid(True)
plt.xlabel('Number of iterations')
plt.ylabel('Cost (J)')
plt.title('Convergence of gradient descent X2')
plt.show()

plt.scatter(X3[:, 1], Y, color='red', label='Training Data')
plt.plot(X3[:, 1], X3.dot(theta_X3), color='green', label='Linear Regression')
plt.rcParams["figure.figsize"] = (10, 6)
plt.grid(True)
plt.xlabel('X3')
plt.ylabel('D3')
plt.title('Linear Regression Fit X3')
plt.legend()
plt.show()

plt.plot(range(1, iterations + 1), cost_history_X3, color='blue')
plt.rcParams["figure.figsize"] = (10, 6)
plt.grid(True)
plt.xlabel('Number of iterations')
plt.ylabel('Cost (J)')
plt.title('Convergence of gradient descent X3')
plt.show()

