# -*- coding: utf-8 -*-
"""HW2_5var_scaling_regularization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SOg30UuTrXCsOAUDDer4Eu72-8aNX8Ek
"""

import numpy as np
import pandas as pd
from google.colab import drive
import matplotlib.pyplot as plt
from IPython.display import display

drive.mount('/content/drive')
file_path = '/content/drive/MyDrive/Machine Learning/Housing.csv'
housing = pd.DataFrame(pd.read_csv(file_path))

from sklearn.model_selection import train_test_split

np.random.seed(0)
housing_training, housing_validation = train_test_split(housing, train_size = 0.8, test_size = 0.2, random_state = 100)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
num_vars = ['area', 'bedrooms', 'bathrooms', 'stories', 'parking']

housing_training[num_vars] = scaler.fit_transform(housing_training[num_vars])
housing_validation[num_vars] = scaler.transform(housing_validation[num_vars])

price_training = housing_training.values[:, 0]
area_training = housing_training.values[:, 1]
bedrooms_training = housing_training.values[:, 2]
bathrooms_training = housing_training.values[:,3]
stories_training = housing_training.values[:,4]
parking_training = housing_training.values[:, 10]

price_validation = housing_validation.values[:, 0]
area_validation = housing_validation.values[:, 1]
bedrooms_validation = housing_validation.values[:, 2]
bathrooms_validation = housing_validation.values[:,3]
stories_validation = housing_validation.values[:,4]
parking_validation = housing_validation.values[:, 10]

numOfRows_training = area_training.size
X0_training = np.ones((numOfRows_training, 1))

numOfRows_validation = area_validation.size
X0_validation = np.ones((numOfRows_validation, 1))

def compute_cost(X, Y, theta):

  predictions = X.dot(theta)
  errors = np.subtract(predictions, Y)
  sqrErrors = np.square(errors)
  J = 1 / (2 * len(Y)) * np.sum(sqrErrors)
  return J

def gradient_descent(X_training, Y_training, X_validation, Y_validation, theta, alpha, lamda, iterations):
  m = len(Y_training)
  cost_history_training = np.zeros(iterations)
  cost_history_validation = np.zeros(iterations)

  for i in range(iterations):
    predictions = X_training.dot(theta)
    errors = np.subtract(predictions, Y_training)

    theta_copy = np.copy(theta)
    theta_copy[0] = 0

    sum_delta = (alpha / m) * (X_training.transpose().dot(errors) + (lamda / m) * theta_copy)
    theta = theta - sum_delta;

    cost_history_training[i] = compute_cost(X_training, Y_training, theta)
    cost_history_validation[i] = compute_cost(X_validation, Y_validation, theta)

  return theta, cost_history_training, cost_history_validation

area_training = area_training.reshape(numOfRows_training,1)
bedrooms_training = bedrooms_training.reshape(numOfRows_training,1)
bathrooms_training = bathrooms_training.reshape(numOfRows_training,1)
stories_training = stories_training.reshape(numOfRows_training,1)
parking_training = parking_training.reshape(numOfRows_training,1)

area_validation = area_validation.reshape(numOfRows_validation,1)
bedrooms_validation = bedrooms_validation.reshape(numOfRows_validation,1)
bathrooms_validation = bathrooms_validation.reshape(numOfRows_validation,1)
stories_validation = stories_validation.reshape(numOfRows_validation,1)
parking_validation = parking_validation.reshape(numOfRows_validation,1)

housing_five_vars_training = np.hstack((X0_training, area_training, bedrooms_training, bathrooms_training, stories_training, parking_training))
housing_five_vars_validation = np.hstack((X0_validation, area_validation, bedrooms_validation, bathrooms_validation, stories_validation, parking_validation))

theta_five_vars = np.zeros(6)
iterations = 2000
alpha = 0.01
lamda = 1

theta_five_vars_training, cost_history_five_vars_training, cost_history_five_vars_validation = gradient_descent(housing_five_vars_training, price_training, housing_five_vars_validation, price_validation, theta_five_vars, alpha, lamda, iterations)

print('Final value of theta housing_five_vars_training =', theta_five_vars_training)
print('cost_history of housing_five_vars_training =', cost_history_five_vars_training)
print('cost_history of housing_five_vars_validation =', cost_history_five_vars_validation)

plt.plot(range(1, iterations + 1), cost_history_five_vars_training, color='blue', label="training loss")
plt.plot(range(1, iterations + 1), cost_history_five_vars_validation, color='orange', label="validation loss")
plt.rcParams["figure.figsize"] = (10, 6)
plt.grid(True)
plt.xlabel('Number of iterations')
plt.ylabel('Cost (J)')
plt.title('Training and Validation Loss Over iterations (five explanitory variables)')
plt.legend()
plt.show()