# -*- coding: utf-8 -*-
"""HW2_11var_scaling_regularization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AtEVINsacYM1NB48QYrnFEfT3bu3-YGA
"""

# @title
import numpy as np
import pandas as pd
from google.colab import drive
import matplotlib.pyplot as plt
from IPython.display import display

drive.mount('/content/drive')
file_path = '/content/drive/MyDrive/Machine Learning/Housing.csv'
housing = pd.DataFrame(pd.read_csv(file_path))

varlist =  ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea']
def binary_map(x):
    return x.map({'yes': 1, 'no': 0})

housing[varlist] = housing[varlist].apply(binary_map)

from sklearn.model_selection import train_test_split
np.random.seed(0)
housing_training, housing_validation = train_test_split(housing, train_size = 0.8, test_size = 0.2, random_state = 100)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
num_vars = ['area', 'bedrooms', 'bathrooms', 'stories', 'parking']

housing_training[num_vars] = scaler.fit_transform(housing_training[num_vars])
housing_validation[num_vars] = scaler.transform(housing_validation[num_vars])

price_training = housing_training.values[:, 0]
area_training = housing_training.values[:, 1]
bedrooms_training = housing_training.values[:, 2]
bathrooms_training = housing_training.values[:,3]
stories_training = housing_training.values[:,4]
mainroad_training = housing_training.values[:,5]
guestroom_training = housing_training.values[:,6]
basement_training = housing_training.values[:,7]
hotwaterheating_training = housing_training.values[:,8]
airconditioning_training = housing_training.values[:,9]
parking_training = housing_training.values[:, 10]
prefarea_training = housing_training.values[:, 11]

price_validation = housing_validation.values[:, 0]
area_validation = housing_validation.values[:, 1]
bedrooms_validation = housing_validation.values[:, 2]
bathrooms_validation = housing_validation.values[:,3]
stories_validation = housing_validation.values[:,4]
mainroad_validation = housing_validation.values[:,5]
guestroom_validation = housing_validation.values[:,6]
basement_validation = housing_validation.values[:,7]
hotwaterheating_validation = housing_validation.values[:,8]
airconditioning_validation = housing_validation.values[:,9]
parking_validation = housing_validation.values[:, 10]
prefarea_validation = housing_validation.values[:, 11]

numOfRows_training = area_training.size
X0_training = np.ones((numOfRows_training, 1))

numOfRows_validation = area_validation.size
X0_validation = np.ones((numOfRows_validation, 1))

def compute_cost(X, Y, theta):

  predictions = X.dot(theta)
  errors = np.subtract(predictions, Y)
  sqrErrors = np.square(errors)
  J = 1 / (2 * len(Y)) * np.sum(sqrErrors)
  return J

def gradient_descent(X_training, Y_training, X_validation, Y_validation, theta, alpha, lamda, iterations):
  m = len(Y_training)
  cost_history_training = np.zeros(iterations)
  cost_history_validation = np.zeros(iterations)

  for i in range(iterations):
    predictions = X_training.dot(theta)
    errors = np.subtract(predictions, Y_training)

    theta_copy = np.copy(theta)
    theta_copy[0] = 0

    sum_delta = (alpha / m) * (X_training.transpose().dot(errors) + (lamda * theta_copy))
    theta = theta - sum_delta;

    cost_history_training[i] = compute_cost(X_training, Y_training, theta)
    cost_history_validation[i] = compute_cost(X_validation, Y_validation, theta)

  return theta, cost_history_training, cost_history_validation

area_training = area_training.reshape(numOfRows_training,1)
bedrooms_training = bedrooms_training.reshape(numOfRows_training,1)
bathrooms_training = bathrooms_training.reshape(numOfRows_training,1)
stories_training = stories_training.reshape(numOfRows_training,1)
mainroad_training = mainroad_training.reshape(numOfRows_training,1)
guestroom_training = guestroom_training.reshape(numOfRows_training,1)
basement_training = basement_training.reshape(numOfRows_training,1)
hotwaterheating_training = hotwaterheating_training.reshape(numOfRows_training,1)
airconditioning_training = airconditioning_training.reshape(numOfRows_training,1)
parking_training = parking_training.reshape(numOfRows_training,1)
prefarea_training = prefarea_training.reshape(numOfRows_training,1)


area_validation = area_validation.reshape(numOfRows_validation,1)
bedrooms_validation = bedrooms_validation.reshape(numOfRows_validation,1)
bathrooms_validation = bathrooms_validation.reshape(numOfRows_validation,1)
stories_validation = stories_validation.reshape(numOfRows_validation,1)
mainroad_validation = mainroad_validation.reshape(numOfRows_validation,1)
guestroom_validation = guestroom_validation.reshape(numOfRows_validation,1)
basement_validation = basement_validation.reshape(numOfRows_validation,1)
hotwaterheating_validation = hotwaterheating_validation.reshape(numOfRows_validation,1)
airconditioning_validation = airconditioning_validation.reshape(numOfRows_validation,1)
parking_validation = parking_validation.reshape(numOfRows_validation,1)
prefarea_validation = prefarea_validation.reshape(numOfRows_validation,1)

housing_eleven_vars_training = np.hstack((X0_training, area_training, bedrooms_training, bathrooms_training, stories_training, mainroad_training, guestroom_training, basement_training, hotwaterheating_training, airconditioning_training, parking_training, prefarea_training))
housing_eleven_vars_validation = np.hstack((X0_validation, area_validation, bedrooms_validation, bathrooms_validation, stories_validation, mainroad_validation, guestroom_validation, basement_validation, hotwaterheating_validation, airconditioning_validation, parking_validation, prefarea_validation))

theta_eleven_vars = np.zeros(12)
iterations = 2000
alpha = 0.01
lamda = .001
theta_eleven_vars_training, cost_history_eleven_vars_training, cost_history_eleven_vars_validation = gradient_descent(housing_eleven_vars_training, price_training, housing_eleven_vars_validation, price_validation, theta_eleven_vars, alpha, lamda, iterations)

print('Final value of theta housing_eleven_vars_training =', theta_eleven_vars_training)
print('cost_history of housing_eleven_vars_training =', cost_history_eleven_vars_training)
print('cost_history of housing_eleven_vars_validation =', cost_history_eleven_vars_validation)

plt.plot(range(1, iterations + 1), cost_history_eleven_vars_training, color='blue', label="training loss")
plt.plot(range(1, iterations + 1), cost_history_eleven_vars_validation, color='orange', label="validation loss")
plt.rcParams["figure.figsize"] = (10, 6)
plt.grid(True)
plt.xlabel('Number of iterations')
plt.ylabel('Cost (J)')
plt.title('Training and Validation Loss Over iterations (eleven explanatory variables)')
plt.legend()
plt.show()