# -*- coding: utf-8 -*-
"""HW3_LogisticRegression_Diabetes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MJylxsr0eXC3K4OUSGMKnfTMScRRwqPC
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')
file_path = '/content/drive/MyDrive/Machine Learning/diabetes.csv'
diabetes = pd.DataFrame(pd.read_csv(file_path))

X = diabetes.iloc[:, 0:8].values
Y = diabetes.iloc[:, 8].values

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size = 0.8,
                                                    test_size = 0.2, random_state = 4)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X0_train = np.ones((X_train[:,0].size, 1))
X0_test = np.ones((X_test[:,0].size, 1))

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train = np.hstack((X0_train, X_train))
X_test = np.hstack((X0_test, X_test))

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def compute_cost(X, Y, theta):
  h = sigmoid(X.dot(theta))
  return -np.mean(Y * np.log(h) + (1 - Y) * np.log(1 - h))

def compute_accuracy(X, Y, theta):
  predictions = (sigmoid(X.dot(theta)) >= 0.5).astype(int)
  return np.mean(predictions == Y)

def gradient_descent(X_training, Y_training, X_validation, Y_validation, theta,
                     alpha, lamda, iterations):
  m = len(Y_training)
  cost_history_training = np.zeros(iterations)
  cost_history_validation = np.zeros(iterations)
  acc_history_training = np.zeros(iterations)
  acc_history_validation = np.zeros(iterations)

  for i in range(iterations):
    predictions = sigmoid(X_training.dot(theta))
    errors = np.subtract(predictions, Y_training)

    theta_copy = np.copy(theta)
    theta_copy[0] = 0

    sum_delta = (alpha / m) * (X_training.transpose().dot(errors) + (lamda * theta_copy))
    theta = theta - sum_delta;

    cost_history_training[i] = compute_cost(X_training, Y_training, theta)
    cost_history_validation[i] = compute_cost(X_validation, Y_validation, theta)
    acc_history_training[i] = compute_accuracy(X_training, Y_training, theta)
    acc_history_validation[i] = compute_accuracy(X_validation, Y_validation, theta)

  return (theta, cost_history_training, cost_history_validation,
  acc_history_training, acc_history_validation)

theta = np.zeros(9)
iterations = 10000
alpha = 0.01
lamda = 0

(theta, cost_history_training, cost_history_validation, acc_history_training,
acc_history_validation) = gradient_descent(X_train, Y_train, X_test, Y_test, theta,
                                           alpha, lamda, iterations)

Y_pred = (sigmoid(X_test.dot(theta)) >= 0.5).astype(int)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)

from sklearn import metrics
print("Accuracy", metrics.accuracy_score(Y_test, Y_pred))
print("Precision", metrics.precision_score(Y_test, Y_pred))
print("Recall", metrics.recall_score(Y_test, Y_pred))
print("F1 Score", metrics.f1_score(Y_test, Y_pred))

print('Final theta =', theta)
print('Final training accuracy =', acc_history_training[-1])
print('Final test accuracy =', acc_history_validation[-1])

import seaborn as sns
class_names = [0,1]

fig, ax = plt.subplots()
tick_marks = np.arange(len(class_names))
plt.xticks(tick_marks, class_names)
plt.yticks(tick_marks, class_names)

sns.heatmap(pd.DataFrame(cm), annot=True, cmap="YlGnBu", fmt='g')
ax.xaxis.set_label_position("top")
plt.tight_layout()
plt.title('Confusion Matrix', y=1.1)
plt.ylabel('Actual label')
plt.xlabel('Predicted label')
plt.show()

plt.figure(figsize=(10, 6))
plt.plot(range(1, iterations + 1), cost_history_training, color='blue', label='training loss')
plt.plot(range(1, iterations + 1), cost_history_validation, color='orange', label='test loss')
plt.xlabel('Number of iterations')
plt.ylabel('Cost (J)')
plt.title('Loss Over Iterations')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
plt.plot(range(1, iterations + 1), acc_history_training, color='blue', label='training accuracy')
plt.plot(range(1, iterations + 1), acc_history_validation, color='orange', label='test accuracy')
plt.xlabel('Number of iterations')
plt.ylabel('Accuracy')
plt.title('Accuracy Over Iterations')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()